version: 0.2

phases:
  build:
    commands:
      - echo 'Building...'
      - echo "<html><body><h1>Hello, CI/CD!</h1><p>Build time: $(date)</p></body></html>" > index.html
      
artifacts:
  files:
    - index.html
